[package]
name = "rustcrack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md2 = "0.10.1"
md5 = "0.7.0"
sha256 = "1.0.3"
base64 = "0.13.0"
